#!/bin/bash
if [ -z "$1" ]
then
 	BRANCH=master
 else
 	BRANCH=$1
 fi
 echo Deploying $BRANCH
 git push
ssh -tt arfanliaqat@142.93.160.27 <<EOF
	set -e
	cd ~/sapiyon/web
	git fetch
	git checkout $BRANCH
	git pull
	export APP_ENV=production
	yarn && yarn build
	rm -rf html && 	mv build html
	exit
EOF
